# Generated by Django 5.2.13 on 2026-05-04 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('type', models.CharField(choices=[('deadline_today', 'Дедлайн сегодня'), ('deadline_soon', 'Скоро дедлайн'), ('overdue', 'Просрочено'), ('project_progress', 'Прогресс проекта'), ('task_completed', 'Задача выполнена'), ('system', 'Системное')], max_length=30, verbose_name='Тип')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('related_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='projects.project', verbose_name='Связанный проект')),
                ('related_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tasks.task', verbose_name='Связанная задача')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ('is_read', '-created_at'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('related_task__isnull', False)), fields=('owner', 'type', 'related_task'), name='unique_task_notification_per_type'), models.UniqueConstraint(condition=models.Q(('related_project__isnull', False)), fields=('owner', 'type', 'related_project'), name='unique_project_notification_per_type')],
            },
        ),
    ]
